### ISSUE TITLE
Failed to flush task queue within 120 seconds.

### ISSUE THREAD

**Issue by Lucien-Chen** [Azure/MachineLearningNotebooks#579]
**Describe the bug**
There were some exceptions "Failed to flush task queue within 120 seconds." when I running automl on local machine with azureml-sdk 1.0.60. How can I solve it?

Provide the following if applicable:
+ Python & SDK version : Python 3.6.7, Azure SDK 1.0.60

<img width="897" alt="螢幕快照 2019-09-18 下午7 37 13" src="https://user-images.githubusercontent.com/26344196/65145289-d015c200-da4b-11e9-8f61-3438020e1102.png">
<img width="709" alt="螢幕快照 2019-09-18 下午7 37 33" src="https://user-images.githubusercontent.com/26344196/65145293-d146ef00-da4b-11e9-96fc-f6fb851c0d44.png">

**Comment by skasturi** [comment]
@Lucien-Chen, Can you please try newer version of the SDK i.e; 1.0.62?

**Comment by Lucien-Chen** [comment]
Hi @skasturi, I got the same errors with SDK 1.0.62.
<img width="939" alt="螢幕快照 2019-09-19 上午11 40 30" src="https://user-images.githubusercontent.com/26344196/65211772-7c9a8700-dad2-11e9-8338-678e560a1569.png">
<img width="934" alt="螢幕快照 2019-09-19 上午11 39 59" src="https://user-images.githubusercontent.com/26344196/65211776-7dcbb400-dad2-11e9-99f4-9c75c1567715.png">

**Comment by v-strudm-msft** [comment]
Thank you for posting this issue.  We see it was addressed by us, but now resolved some time ago. Our apologies. We will close it. Should you still need assistance with this or another issue, please re-post and we will respond promptly.

**Comment by kracekumar** [comment]
I'm facing a similar issue. 

```
# high level code
$python sync_result_to_azureml.py experiment --exp exp_name
$cat sync_result_to_azureml.py 
...
def authenticate():
    global auth
    if auth:
        return auth
    auth = ServicePrincipalAuthentication(tenant_id=os.environ.get('ARM_TENANT_ID'),
                                          service_principal_id=os.environ.get('ARM_CLIENT_ID'),
                                          service_principal_password=os.environ.get('ARM_CLIENT_SECRET'))
    return auth


def get_or_create_exp(name, _create_in_cloud=True):
    auth = authenticate()
    workspace = Workspace.from_config(auth=auth)
    experiment = Experiment(workspace=workspace, name=name,
                            _create_in_cloud=_create_in_cloud)
    return experiment


@click.command()
@click.option('--exp', required=True)
def experiment(exp):
    # Only get the experiment already in the workspace.
    experiment = get_or_create_exp(exp, _create_in_cloud=False)
    # print(experiment.archive())
    list_runs = experiment.get_runs()
    details = []
    for run in list_runs:
        # print(run.id, run.get_details())
        details.append(run.get_details())
        run.download_files(output_directory=f'{exp}_dl/{run.id}')
    dict_to_table(title=f'Experiment {exp} run details', data=details)
...
```

### output on macOSx

```
...
raise AzureMLException("Failed to flush task queue within {} seconds".format(timeout_seconds))
azureml._common.exceptions.AzureMLException: AzureMLException:
	Message: Failed to flush task queue within 120 seconds
	InnerException None
	ErrorResponse
{
    "error": {
        "message": "Failed to flush task queue within 120 seconds"
    }
}
```

### Dependencies

```
$pip freeze | grep azureml                                                                                                                                                             
azureml-automl-core==1.10.0.post1
azureml-automl-runtime==1.10.0.post1
azureml-contrib-notebook==1.10.0
azureml-core==1.10.0
azureml-dataprep==1.9.2
azureml-dataprep-native==14.2.1
azureml-dataset-runtime==1.10.0
azureml-defaults==1.10.0
azureml-explain-model==1.10.0
azureml-interpret==1.10.0
azureml-model-management-sdk==1.0.1b6.post1
azureml-pipeline==1.10.0
azureml-pipeline-core==1.10.0
azureml-pipeline-steps==1.10.0
azureml-sdk==1.10.0
azureml-telemetry==1.10.0
azureml-train==1.10.0
azureml-train-automl==1.10.0
azureml-train-automl-client==1.10.0
azureml-train-automl-runtime==1.10.0
azureml-train-core==1.10.0
azureml-train-restclients-hyperdrive==1.10.0
azureml-widgets==1.10.0
```

### Python Version 
```
$python --version                                                                                                                                                                                           
Python 3.6.9
```

Should I open a new issue?

**Comment by v-strudm-msft** [comment]
@CESARDELATORRE please take a look. Thanks!

**Comment by lostmygithubaccount** [comment]
@kracekumar please do open a new issue if still experiencing this after running `pip install --upgrade azureml-sdk[automl]`
